package model.bean;
// Generated 30/03/2019 15:24:47 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Cidade generated by hbm2java
 */
public class Cidade  implements java.io.Serializable {


     private Integer id;
     private Estado estado;
     private String nome;
     private String sigla;
     private Date dtCadastro;

    public Cidade() {
    }

    public Cidade(Estado estado, String nome, String sigla, Date dtCadastro) {
       this.estado = estado;
       this.nome = nome;
       this.sigla = sigla;
       this.dtCadastro = dtCadastro;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSigla() {
        return this.sigla;
    }
    
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }
    public Date getDtCadastro() {
        return this.dtCadastro;
    }
    
    public void setDtCadastro(Date dtCadastro) {
        this.dtCadastro = dtCadastro;
    }




}


