package model.bean;
// Generated 20/04/2019 15:26:40 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Consulta generated by hbm2java
 */
public class Consulta  implements java.io.Serializable {


     private Integer id;
     private Paciente paciente;
     private Agenda agenda;
     private String observacao;
     private String observacaoReceita;
     private String observacaoExame;
     private Integer status;
     private Date dtCadastro;
     private Set receitas = new HashSet(0);
     private Set exames = new HashSet(0);

    public Consulta() {
    }

    public Consulta(Paciente paciente, Agenda agenda, String observacao, String observacaoReceita, String observacaoExame, Integer status, Date dtCadastro, Set receitas, Set exames) {
       this.paciente = paciente;
       this.agenda = agenda;
       this.observacao = observacao;
       this.observacaoReceita = observacaoReceita;
       this.observacaoExame = observacaoExame;
       this.status = status;
       this.dtCadastro = dtCadastro;
       this.receitas = receitas;
       this.exames = exames;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }
    public Agenda getAgenda() {
        return this.agenda;
    }
    
    public void setAgenda(Agenda agenda) {
        this.agenda = agenda;
    }
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }
    public String getObservacaoReceita() {
        return this.observacaoReceita;
    }
    
    public void setObservacaoReceita(String observacaoReceita) {
        this.observacaoReceita = observacaoReceita;
    }
    public String getObservacaoExame() {
        return this.observacaoExame;
    }
    
    public void setObservacaoExame(String observacaoExame) {
        this.observacaoExame = observacaoExame;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Date getDtCadastro() {
        return this.dtCadastro;
    }
    
    public void setDtCadastro(Date dtCadastro) {
        this.dtCadastro = dtCadastro;
    }
    public Set getReceitas() {
        return this.receitas;
    }
    
    public void setReceitas(Set receitas) {
        this.receitas = receitas;
    }
    public Set getExames() {
        return this.exames;
    }
    
    public void setExames(Set exames) {
        this.exames = exames;
    }




}


