package model.bean;
// Generated 20/04/2019 15:26:40 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Exame generated by hbm2java
 */
public class Exame  implements java.io.Serializable {


     private Integer id;
     private Tipoexame tipoexame;
     private Consulta consulta;
     private String observacao;
     private Integer status;
     private Date dtRealizacao;
     private Date dtCadastro;
     private Set resultados = new HashSet(0);

    public Exame() {
    }

    public Exame(Tipoexame tipoexame, Consulta consulta, String observacao, Integer status, Date dtRealizacao, Date dtCadastro, Set resultados) {
       this.tipoexame = tipoexame;
       this.consulta = consulta;
       this.observacao = observacao;
       this.status = status;
       this.dtRealizacao = dtRealizacao;
       this.dtCadastro = dtCadastro;
       this.resultados = resultados;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tipoexame getTipoexame() {
        return this.tipoexame;
    }
    
    public void setTipoexame(Tipoexame tipoexame) {
        this.tipoexame = tipoexame;
    }
    public Consulta getConsulta() {
        return this.consulta;
    }
    
    public void setConsulta(Consulta consulta) {
        this.consulta = consulta;
    }
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Date getDtRealizacao() {
        return this.dtRealizacao;
    }
    
    public void setDtRealizacao(Date dtRealizacao) {
        this.dtRealizacao = dtRealizacao;
    }
    public Date getDtCadastro() {
        return this.dtCadastro;
    }
    
    public void setDtCadastro(Date dtCadastro) {
        this.dtCadastro = dtCadastro;
    }
    public Set getResultados() {
        return this.resultados;
    }
    
    public void setResultados(Set resultados) {
        this.resultados = resultados;
    }




}


