package model.bean;
// Generated 20/04/2019 15:26:40 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Fabricante generated by hbm2java
 */
public class Fabricante  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private Integer status;
     private Date dtCadastro;
     private Set medicamentos = new HashSet(0);

    public Fabricante() {
    }

    public Fabricante(String nome, Integer status, Date dtCadastro, Set medicamentos) {
       this.nome = nome;
       this.status = status;
       this.dtCadastro = dtCadastro;
       this.medicamentos = medicamentos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Date getDtCadastro() {
        return this.dtCadastro;
    }
    
    public void setDtCadastro(Date dtCadastro) {
        this.dtCadastro = dtCadastro;
    }
    public Set getMedicamentos() {
        return this.medicamentos;
    }
    
    public void setMedicamentos(Set medicamentos) {
        this.medicamentos = medicamentos;
    }




}


