package model.bean;
// Generated 20/04/2019 15:26:40 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Medicoespecialidade generated by hbm2java
 */
public class Medicoespecialidade  implements java.io.Serializable {


     private Integer id;
     private Medico medico;
     private Especialidade especialidade;
     private Date dtCadastro;

    public Medicoespecialidade() {
    }

    public Medicoespecialidade(Medico medico, Especialidade especialidade, Date dtCadastro) {
       this.medico = medico;
       this.especialidade = especialidade;
       this.dtCadastro = dtCadastro;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Medico getMedico() {
        return this.medico;
    }
    
    public void setMedico(Medico medico) {
        this.medico = medico;
    }
    public Especialidade getEspecialidade() {
        return this.especialidade;
    }
    
    public void setEspecialidade(Especialidade especialidade) {
        this.especialidade = especialidade;
    }
    public Date getDtCadastro() {
        return this.dtCadastro;
    }
    
    public void setDtCadastro(Date dtCadastro) {
        this.dtCadastro = dtCadastro;
    }




}


