package model.bean;
// Generated 20/04/2019 15:26:40 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Paciente generated by hbm2java
 */
public class Paciente  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private String sexo;
     private String rg;
     private String cpf;
     private Date dtNascimento;
     private String email;
     private String foneResidencial;
     private String foneCelular;
     private String enderecoCep;
     private String enderecoLogradouro;
     private String enderecoNumero;
     private String enderecoCidade;
     private String enderecoUf;
     private Date dtCadastro;
     private Set consultas = new HashSet(0);

    public Paciente() {
    }

    public Paciente(String nome, String sexo, String rg, String cpf, Date dtNascimento, String email, String foneResidencial, String foneCelular, String enderecoCep, String enderecoLogradouro, String enderecoNumero, String enderecoCidade, String enderecoUf, Date dtCadastro, Set consultas) {
       this.nome = nome;
       this.sexo = sexo;
       this.rg = rg;
       this.cpf = cpf;
       this.dtNascimento = dtNascimento;
       this.email = email;
       this.foneResidencial = foneResidencial;
       this.foneCelular = foneCelular;
       this.enderecoCep = enderecoCep;
       this.enderecoLogradouro = enderecoLogradouro;
       this.enderecoNumero = enderecoNumero;
       this.enderecoCidade = enderecoCidade;
       this.enderecoUf = enderecoUf;
       this.dtCadastro = dtCadastro;
       this.consultas = consultas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public Date getDtNascimento() {
        return this.dtNascimento;
    }
    
    public void setDtNascimento(Date dtNascimento) {
        this.dtNascimento = dtNascimento;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getFoneResidencial() {
        return this.foneResidencial;
    }
    
    public void setFoneResidencial(String foneResidencial) {
        this.foneResidencial = foneResidencial;
    }
    public String getFoneCelular() {
        return this.foneCelular;
    }
    
    public void setFoneCelular(String foneCelular) {
        this.foneCelular = foneCelular;
    }
    public String getEnderecoCep() {
        return this.enderecoCep;
    }
    
    public void setEnderecoCep(String enderecoCep) {
        this.enderecoCep = enderecoCep;
    }
    public String getEnderecoLogradouro() {
        return this.enderecoLogradouro;
    }
    
    public void setEnderecoLogradouro(String enderecoLogradouro) {
        this.enderecoLogradouro = enderecoLogradouro;
    }
    public String getEnderecoNumero() {
        return this.enderecoNumero;
    }
    
    public void setEnderecoNumero(String enderecoNumero) {
        this.enderecoNumero = enderecoNumero;
    }
    public String getEnderecoCidade() {
        return this.enderecoCidade;
    }
    
    public void setEnderecoCidade(String enderecoCidade) {
        this.enderecoCidade = enderecoCidade;
    }
    public String getEnderecoUf() {
        return this.enderecoUf;
    }
    
    public void setEnderecoUf(String enderecoUf) {
        this.enderecoUf = enderecoUf;
    }
    public Date getDtCadastro() {
        return this.dtCadastro;
    }
    
    public void setDtCadastro(Date dtCadastro) {
        this.dtCadastro = dtCadastro;
    }
    public Set getConsultas() {
        return this.consultas;
    }
    
    public void setConsultas(Set consultas) {
        this.consultas = consultas;
    }




}


