package model.bean;
// Generated 20/04/2019 15:26:40 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Receita generated by hbm2java
 */
public class Receita  implements java.io.Serializable {


     private Integer id;
     private Medicamento medicamento;
     private Consulta consulta;
     private String observacao;
     private Date dtCadastro;

    public Receita() {
    }

    public Receita(Medicamento medicamento, Consulta consulta, String observacao, Date dtCadastro) {
       this.medicamento = medicamento;
       this.consulta = consulta;
       this.observacao = observacao;
       this.dtCadastro = dtCadastro;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Medicamento getMedicamento() {
        return this.medicamento;
    }
    
    public void setMedicamento(Medicamento medicamento) {
        this.medicamento = medicamento;
    }
    public Consulta getConsulta() {
        return this.consulta;
    }
    
    public void setConsulta(Consulta consulta) {
        this.consulta = consulta;
    }
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }
    public Date getDtCadastro() {
        return this.dtCadastro;
    }
    
    public void setDtCadastro(Date dtCadastro) {
        this.dtCadastro = dtCadastro;
    }




}


