package model.bean;
// Generated 20/04/2019 15:26:40 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Recepcionista generated by hbm2java
 */
public class Recepcionista  implements java.io.Serializable {


     private Integer id;
     private Usuario usuario;
     private String nome;
     private String rg;
     private String cpf;
     private String email;
     private String foneCelular;
     private String foneResidencial;
     private Integer status;
     private Date dtCadastro;

    public Recepcionista() {
    }

    public Recepcionista(Usuario usuario, String nome, String rg, String cpf, String email, String foneCelular, String foneResidencial, Integer status, Date dtCadastro) {
       this.usuario = usuario;
       this.nome = nome;
       this.rg = rg;
       this.cpf = cpf;
       this.email = email;
       this.foneCelular = foneCelular;
       this.foneResidencial = foneResidencial;
       this.status = status;
       this.dtCadastro = dtCadastro;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getFoneCelular() {
        return this.foneCelular;
    }
    
    public void setFoneCelular(String foneCelular) {
        this.foneCelular = foneCelular;
    }
    public String getFoneResidencial() {
        return this.foneResidencial;
    }
    
    public void setFoneResidencial(String foneResidencial) {
        this.foneResidencial = foneResidencial;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Date getDtCadastro() {
        return this.dtCadastro;
    }
    
    public void setDtCadastro(Date dtCadastro) {
        this.dtCadastro = dtCadastro;
    }




}


