package model.bean;
// Generated 20/04/2019 15:26:40 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tela generated by hbm2java
 */
public class Tela  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private Integer status;
     private Date dtCadastro;
     private Set acessos = new HashSet(0);

    public Tela() {
    }

    public Tela(String nome, Integer status, Date dtCadastro, Set acessos) {
       this.nome = nome;
       this.status = status;
       this.dtCadastro = dtCadastro;
       this.acessos = acessos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Date getDtCadastro() {
        return this.dtCadastro;
    }
    
    public void setDtCadastro(Date dtCadastro) {
        this.dtCadastro = dtCadastro;
    }
    public Set getAcessos() {
        return this.acessos;
    }
    
    public void setAcessos(Set acessos) {
        this.acessos = acessos;
    }




}


