package model.bean;
// Generated 31/03/2019 16:11:57 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer id;
     private String login;
     private String senha;
     private Integer status;
     private Date dtCadastro;

    public Usuario() {
    }

    public Usuario(String login, String senha, Integer status, Date dtCadastro) {
       this.login = login;
       this.senha = senha;
       this.status = status;
       this.dtCadastro = dtCadastro;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Date getDtCadastro() {
        return this.dtCadastro;
    }
    
    public void setDtCadastro(Date dtCadastro) {
        this.dtCadastro = dtCadastro;
    }




}


